webtalk_init -webtalk_dir C:/Users/nisha/OneDrive/Desktop/Digital Filters/DS_Project_ANC_Digital_Filters/Week_1/Week_1.sim/sim_1/behav/xsim/xsim.dir/trial1_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Mar 14 20:14:55 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9e190ae6-3ef8-4c67-8e66-12082ab22a04" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "91ddf5f6ff02473091a8facd2598ac29" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i7-12700H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "160 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7976_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2917167758 -regid "" -xml C:/Users/nisha/OneDrive/Desktop/Digital Filters/DS_Project_ANC_Digital_Filters/Week_1/Week_1.sim/sim_1/behav/xsim/xsim.dir/trial1_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/nisha/OneDrive/Desktop/Digital Filters/DS_Project_ANC_Digital_Filters/Week_1/Week_1.sim/sim_1/behav/xsim/xsim.dir/trial1_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/nisha/OneDrive/Desktop/Digital Filters/DS_Project_ANC_Digital_Filters/Week_1/Week_1.sim/sim_1/behav/xsim/xsim.dir/trial1_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
